trigger:
  batch: true
  branches:
    include:
      - PHP-7.4
      - PHP-8.0
      - PHP-8.1
      - master
  paths:
    exclude:
      - docs/*
      - NEWS
      - UPGRADING
      - UPGRADING.INTERNALS
      - README.md
      - CONTRIBUTING.md
      - CODING_STANDARDS.md

schedules:
  - cron: "0 1 * * *"
    displayName: Nightly build
    branches:
      include:
        - PHP-7.4
        - PHP-8.0
        - PHP-8.1
        - master

jobs:
  - template: azure/i386/job.yml
    parameters:
      configurationName: I386_DEBUG_ZTS
      configurationParameters: '--enable-debug --enable-zts'
  - ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
    - template: azure/i386/job.yml
      parameters:
        configurationName: I386_DEBUG_NTS
        configurationParameters: '--enable-debug --disable-zts'
    - template: azure/i386/job.yml
      parameters:
        configurationName: I386_RELEASE_NTS
        configurationParameters: '--disable-debug --disable-zts'
    - template: azure/i386/job.yml
      parameters:
        configurationName: I386_RELEASE_ZTS
        configurationParameters: '--disable-debug --enable-zts'
